class SuraModel {
   String suraEn;
   String suraAr;
   String suraVerses;
   String suraNum;
  SuraModel({
    required this.suraEn,
    required this.suraAr,
    required this.suraVerses,
    required this.suraNum,
  });
  static final List<SuraModel> suras = [
    SuraModel(suraEn: "Al-Fatihah", suraAr: "الفاتحة", suraVerses: "7", suraNum: "1"),
    SuraModel(suraEn: "Al-Baqarah", suraAr: "البقرة", suraVerses: "286", suraNum: "2"),
    SuraModel(suraEn: "Aal-E-Imran", suraAr: "آل عمران", suraVerses: "200", suraNum: "3"),
    SuraModel(suraEn: "An-Nisa", suraAr: "النساء", suraVerses: "176", suraNum: "4"),
    SuraModel(suraEn: "Al-Maidah", suraAr: "المائدة", suraVerses: "120", suraNum: "5"),
    SuraModel(suraEn: "Al-An'am", suraAr: "الأنعام", suraVerses: "165", suraNum: "6"),
    SuraModel(suraEn: "Al-A'raf", suraAr: "الأعراف", suraVerses: "206", suraNum: "7"),
    SuraModel(suraEn: "Al-Anfal", suraAr: "الأنفال", suraVerses: "75", suraNum: "8"),
    SuraModel(suraEn: "At-Tawbah", suraAr: "التوبة", suraVerses: "129", suraNum: "9"),
    SuraModel(suraEn: "Yunus", suraAr: "يونس", suraVerses: "109", suraNum: "10"),
    SuraModel(suraEn: "Hud", suraAr: "هود", suraVerses: "123", suraNum: "11"),
    SuraModel(suraEn: "Yusuf", suraAr: "يوسف", suraVerses: "111", suraNum: "12"),
    SuraModel(suraEn: "Ar-Ra'd", suraAr: "الرعد", suraVerses: "43", suraNum: "13"),
    SuraModel(suraEn: "Ibrahim", suraAr: "إبراهيم", suraVerses: "52", suraNum: "14"),
    SuraModel(suraEn: "Al-Hijr", suraAr: "الحجر", suraVerses: "99", suraNum: "15"),
    SuraModel(suraEn: "An-Nahl", suraAr: "النحل", suraVerses: "128", suraNum: "16"),
    SuraModel(suraEn: "Al-Isra", suraAr: "الإسراء", suraVerses: "111", suraNum: "17"),
    SuraModel(suraEn: "Al-Kahf", suraAr: "الكهف", suraVerses: "110", suraNum: "18"),
    SuraModel(suraEn: "Maryam", suraAr: "مريم", suraVerses: "98", suraNum: "19"),
    SuraModel(suraEn: "Ta-Ha", suraAr: "طه", suraVerses: "135", suraNum: "20"),
    SuraModel(suraEn: "Al-Anbiya", suraAr: "الأنبياء", suraVerses: "112", suraNum: "21"),
    SuraModel(suraEn: "Al-Hajj", suraAr: "الحج", suraVerses: "78", suraNum: "22"),
    SuraModel(suraEn: "Al-Mu’minun", suraAr: "المؤمنون", suraVerses: "118", suraNum: "23"),
    SuraModel(suraEn: "An-Nur", suraAr: "النور", suraVerses: "64", suraNum: "24"),
    SuraModel(suraEn: "Al-Furqan", suraAr: "الفرقان", suraVerses: "77", suraNum: "25"),
    SuraModel(suraEn: "Ash-Shu'ara", suraAr: "الشعراء", suraVerses: "227", suraNum: "26"),
    SuraModel(suraEn: "An-Naml", suraAr: "النمل", suraVerses: "93", suraNum: "27"),
    SuraModel(suraEn: "Al-Qasas", suraAr: "القصص", suraVerses: "88", suraNum: "28"),
    SuraModel(suraEn: "Al-Ankabut", suraAr: "العنكبوت", suraVerses: "69", suraNum: "29"),
    SuraModel(suraEn: "Ar-Rum", suraAr: "الروم", suraVerses: "60", suraNum: "30"),
    SuraModel(suraEn: "Luqman", suraAr: "لقمان", suraVerses: "34", suraNum: "31"),
    SuraModel(suraEn: "As-Sajda", suraAr: "السجدة", suraVerses: "30", suraNum: "32"),
    SuraModel(suraEn: "Al-Ahzab", suraAr: "الأحزاب", suraVerses: "73", suraNum: "33"),
    SuraModel(suraEn: "Saba", suraAr: "سبأ", suraVerses: "54", suraNum: "34"),
    SuraModel(suraEn: "Fatir", suraAr: "فاطر", suraVerses: "45", suraNum: "35"),
    SuraModel(suraEn: "Ya-Sin", suraAr: "يس", suraVerses: "83", suraNum: "36"),
    SuraModel(suraEn: "As-Saffat", suraAr: "الصافات", suraVerses: "182", suraNum: "37"),
    SuraModel(suraEn: "Sad", suraAr: "ص", suraVerses: "88", suraNum: "38"),
    SuraModel(suraEn: "Az-Zumar", suraAr: "الزمر", suraVerses: "75", suraNum: "39"),
    SuraModel(suraEn: "Ghafir", suraAr: "غافر", suraVerses: "85", suraNum: "40"),
    SuraModel(suraEn: "Fussilat", suraAr: "فصلت", suraVerses: "54", suraNum: "41"),
    SuraModel(suraEn: "Ash-Shura", suraAr: "الشورى", suraVerses: "53", suraNum: "42"),
    SuraModel(suraEn: "Az-Zukhruf", suraAr: "الزخرف", suraVerses: "89", suraNum: "43"),
    SuraModel(suraEn: "Ad-Dukhan", suraAr: "الدخان", suraVerses: "59", suraNum: "44"),
    SuraModel(suraEn: "Al-Jathiya", suraAr: "الجاثية", suraVerses: "37", suraNum: "45"),
    SuraModel(suraEn: "Al-Ahqaf", suraAr: "الأحقاف", suraVerses: "35", suraNum: "46"),
    SuraModel(suraEn: "Muhammad", suraAr: "محمد", suraVerses: "38", suraNum: "47"),
    SuraModel(suraEn: "Al-Fath", suraAr: "الفتح", suraVerses: "29", suraNum: "48"),
    SuraModel(suraEn: "Al-Hujurat", suraAr: "الحجرات", suraVerses: "18", suraNum: "49"),
    SuraModel(suraEn: "Qaf", suraAr: "ق", suraVerses: "45", suraNum: "50"),
    SuraModel(suraEn: "Adh-Dhariyat", suraAr: "الذاريات", suraVerses: "60", suraNum: "51"),
    SuraModel(suraEn: "At-Tur", suraAr: "الطور", suraVerses: "49", suraNum: "52"),
    SuraModel(suraEn: "An-Najm", suraAr: "النجم", suraVerses: "62", suraNum: "53"),
    SuraModel(suraEn: "Al-Qamar", suraAr: "القمر", suraVerses: "55", suraNum: "54"),
    SuraModel(suraEn: "Ar-Rahman", suraAr: "الرحمن", suraVerses: "78", suraNum: "55"),
    SuraModel(suraEn: "Al-Waqia", suraAr: "الواقعة", suraVerses: "96", suraNum: "56"),
    SuraModel(suraEn: "Al-Hadid", suraAr: "الحديد", suraVerses: "29", suraNum: "57"),
    SuraModel(suraEn: "Al-Mujadila", suraAr: "المجادلة", suraVerses: "22", suraNum: "58"),
    SuraModel(suraEn: "Al-Hashr", suraAr: "الحشر", suraVerses: "24", suraNum: "59"),
    SuraModel(suraEn: "Al-Mumtahina", suraAr: "الممتحنة", suraVerses: "13", suraNum: "60"),
    SuraModel(suraEn: "As-Saff", suraAr: "الصف", suraVerses: "14", suraNum: "61"),
    SuraModel(suraEn: "Al-Jumua", suraAr: "الجمعة", suraVerses: "11", suraNum: "62"),
    SuraModel(suraEn: "Al-Munafiqun", suraAr: "المنافقون", suraVerses: "11", suraNum: "63"),
    SuraModel(suraEn: "At-Taghabun", suraAr: "التغابن", suraVerses: "18", suraNum: "64"),
    SuraModel(suraEn: "At-Talaq", suraAr: "الطلاق", suraVerses: "12", suraNum: "65"),
    SuraModel(suraEn: "At-Tahrim", suraAr: "التحريم", suraVerses: "12", suraNum: "66"),
    SuraModel(suraEn: "Al-Mulk", suraAr: "الملك", suraVerses: "30", suraNum: "67"),
    SuraModel(suraEn: "Al-Qalam", suraAr: "القلم", suraVerses: "52", suraNum: "68"),
    SuraModel(suraEn: "Al-Haqqa", suraAr: "الحاقة", suraVerses: "52", suraNum: "69"),
    SuraModel(suraEn: "Al-Ma'arij", suraAr: "المعارج", suraVerses: "44", suraNum: "70"),
    SuraModel(suraEn: "Nuh", suraAr: "نوح", suraVerses: "28", suraNum: "71"),
    SuraModel(suraEn: "Al-Jinn", suraAr: "الجن", suraVerses: "28", suraNum: "72"),
    SuraModel(suraEn: "Al-Muzzammil", suraAr: "المزمل", suraVerses: "20", suraNum: "73"),
    SuraModel(suraEn: "Al-Muddathir", suraAr: "المدثر", suraVerses: "56", suraNum: "74"),
    SuraModel(suraEn: "Al-Qiyama", suraAr: "القيامة", suraVerses: "40", suraNum: "75"),
    SuraModel(suraEn: "Al-Insan", suraAr: "الإنسان", suraVerses: "31", suraNum: "76"),
    SuraModel(suraEn: "Al-Mursalat", suraAr: "المرسلات", suraVerses: "50", suraNum: "77"),
    SuraModel(suraEn: "An-Naba", suraAr: "النبأ", suraVerses: "40", suraNum: "78"),
    SuraModel(suraEn: "An-Nazi'at", suraAr: "النازعات", suraVerses: "46", suraNum: "79"),
    SuraModel(suraEn: "Abasa", suraAr: "عبس", suraVerses: "42", suraNum: "80"),
    SuraModel(suraEn: "At-Takwir", suraAr: "التكوير", suraVerses: "29", suraNum: "81"),
    SuraModel(suraEn: "Al-Infitar", suraAr: "الانفطار", suraVerses: "19", suraNum: "82"),
    SuraModel(suraEn: "Al-Mutaffifin", suraAr: "المطففين", suraVerses: "36", suraNum: "83"),
    SuraModel(suraEn: "Al-Inshiqaq", suraAr: "الانشقاق", suraVerses: "25", suraNum: "84"),
    SuraModel(suraEn: "Al-Buruj", suraAr: "البروج", suraVerses: "22", suraNum: "85"),
    SuraModel(suraEn: "At-Tariq", suraAr: "الطارق", suraVerses: "17", suraNum: "86"),
    SuraModel(suraEn: "Al-Ala", suraAr: "الأعلى", suraVerses: "19", suraNum: "87"),
    SuraModel(suraEn: "Al-Ghashiyah", suraAr: "الغاشية", suraVerses: "26", suraNum: "88"),
    SuraModel(suraEn: "Al-Fajr", suraAr: "الفجر", suraVerses: "30", suraNum: "89"),
    SuraModel(suraEn: "Al-Balad", suraAr: "البلد", suraVerses: "20", suraNum: "90"),
    SuraModel(suraEn: "Ash-Shams", suraAr: "الشمس", suraVerses: "15", suraNum: "91"),
    SuraModel(suraEn: "Al-Lail", suraAr: "الليل", suraVerses: "21", suraNum: "92"),
    SuraModel(suraEn: "Ad-Duhaa", suraAr: "الضحى", suraVerses: "11", suraNum: "93"),
    SuraModel(suraEn: "Ash-Sharh", suraAr: "الشرح", suraVerses: "8", suraNum: "94"),
    SuraModel(suraEn: "At-Tin", suraAr: "التين", suraVerses: "8", suraNum: "95"),
    SuraModel(suraEn: "Al-Alaq", suraAr: "العلق", suraVerses: "19", suraNum: "96"),
    SuraModel(suraEn: "Al-Qadr", suraAr: "القدر", suraVerses: "5", suraNum: "97"),
    SuraModel(suraEn: "Al-Bayyina", suraAr: "البينة", suraVerses: "8", suraNum: "98"),
    SuraModel(suraEn: "Az-Zalzala", suraAr: "الزلزلة", suraVerses: "8", suraNum: "99"),
    SuraModel(suraEn: "Al-Adiyat", suraAr: "العاديات", suraVerses: "11", suraNum: "100"),
    SuraModel(suraEn: "Al-Qaria", suraAr: "القارعة", suraVerses: "11", suraNum: "101"),
    SuraModel(suraEn: "At-Takathur", suraAr: "التكاثر", suraVerses: "8", suraNum: "102"),
    SuraModel(suraEn: "Al-Asr", suraAr: "العصر", suraVerses: "3", suraNum: "103"),
    SuraModel(suraEn: "Al-Humazah", suraAr: "الهمزة", suraVerses: "9", suraNum: "104"),
    SuraModel(suraEn: "Al-Fil", suraAr: "الفيل", suraVerses: "5", suraNum: "105"),
    SuraModel(suraEn: "Quraish", suraAr: "قريش", suraVerses: "4", suraNum: "106"),
    SuraModel(suraEn: "Al-Ma'un", suraAr: "الماعون", suraVerses: "7", suraNum: "107"),
    SuraModel(suraEn: "Al-Kawthar", suraAr: "الكوثر", suraVerses: "3", suraNum: "108"),
    SuraModel(suraEn: "Al-Kafiroon", suraAr: "الكافرون", suraVerses: "6", suraNum: "109"),
    SuraModel(suraEn: "An-Nasr", suraAr: "النصر", suraVerses: "3", suraNum: "110"),
    SuraModel(suraEn: "Al-Masad", suraAr: "المسد", suraVerses: "5", suraNum: "111"),
    SuraModel(suraEn: "Al-Ikhlas", suraAr: "الإخلاص", suraVerses: "4", suraNum: "112"),
    SuraModel(suraEn: "Al-Falaq", suraAr: "الفلق", suraVerses: "5", suraNum: "113"),
    SuraModel(suraEn: "An-Nas", suraAr: "الناس", suraVerses: "6", suraNum: "114"),
  ];
}
